### PR TITLE
allow port to be configured or defaulted

### PR DESCRIPTION
**Pull request by imavroukakis**
uses `URI` to validate a host or host/port combination

### CODE REVIEW

**Comment by michaeldejong** [comment]
Overall looking very good! Especially +1 for the added test :)

I'd like to make some changes though:

* **No need to rearrange the imports**. We use a slightly different ordering than the IntelliJ defaults, and it's our fault for not including these formatting rules in the repository (we'll add them soon™️). Same goes for a short contribution guide 😉 .
* **Resolving the star imports**, but again we should have included the formatting rules file.
* **The `withConsulHostPort(host, port)` method is somewhat redundant**. Ideally we want to keep the `Builder` API unchanged, and simply interpret the URL (if specified using the already existing methods) and default that to 8500 if it's not set. Easily fixed.

I'll merge this now, and then finish it up on monday after which I'll also make a new bugfix release: 1.5.1. So stay tuned!

Thanks @imavroukakis for your contribution and being `consultant`'s first external contributor! 🎉

**Comment by imavroukakis** [comment]
You're very welcome :-) The only reason I made it as a different method, was to highlight the difference between simply using another host (without a port) and another host on a different port.  If you where to swap out the String for a java.net.URI , you pass on that responsibility to the client to have a well formed URI, but they have to deal with the exception.
The alternative is to simply check the existence of a port on the URI and create a new instance with the port set. This way you can re-use the existing method.

**Comment by michaeldejong** [comment]
I think I might also have forgotten about the fact that HTTP's default port is 80, so what it should do is:

* `localhost` should become `http://localhost:8500`
* `localhost:8500` should become `http://localhost:8500`.
* `http://localhost` should become `http://localhost`
* `http://localhost:8500` should become `http://localhost:8500`

Thoughts?

**Comment by imavroukakis** [comment]
One approach would be to use a reliable regex pattern to break down the String URI  to tokens, identify each token, and construct a URL via the `URL(String protocol,String host,int port,String file)` and then call toURI(), so that it be fed to HttpGet and friends.

**Pull request merged**
