### PR TITLE
Add the support for ownership

### PR DESCRIPTION
**Pull request by alexnederlof**
Mainly so that when a variable is declared somewhere after the
application starts, it can still be picked up by consultant, because we
can set teh ownership to ALL.

See https://github.com/Netflix/governator/wiki/Configuration-Mapping#dynamic-configuration

Also supports variable substition, and I added the consultant variables
as the default

See
https://github.com/Netflix/governator/wiki/Configuration-Mapping#configurationkey

RFR @michaeldejong @AlexKolpa

### CODE REVIEW

**Comment by michaeldejong** [comment]
Took me a while to figure out what this exactly aims to achieve.

Can you at least add a couple of tests? I can already spot one simple bug. It's `dc` not `dataCenter`.

**Comment by alexnederlof** [comment]
I'll add tests. The `dataCenter` is on purpose, because it's more readable when out of context. For example, if you stumble upon a class where `@Configuration("requestlogger.${dc}") is used, you know less than when `dataCenter` is used. Don't you think?

**Comment by michaeldejong** [comment]
No, in Consul `dc` is a thing. Besides this will be a good source of bugs if this is inconsistent with the rest of Consultant.

**Comment by alexnederlof** [comment]
Perhaps I should rename it to `consul.dc` in that case, to clear things up.

**Comment by michaeldejong** [comment]
Try following these naming conventions: https://github.com/Magnetme/consultant/blob/master/src/main/java/me/magnet/consultant/ServiceIdentifier.java#L121-L134

**Comment by michaeldejong** [comment]
Closing due to inactivity. Reopen if needed.

**Pull request closed without merging**
