### PR TITLE
Do not log as error when the service consultant is bound to is shutting down

### PR DESCRIPTION
**Pull request by rogierslag**
This is throwing quite some (useless) errors, so we simply check the message
to determine when this is the case.

If this is happening, dont log it as an error (since its not an error)

@Magnetme/developers ready for review!

### CODE REVIEW

**Comment by AlexKolpa** [comment]
I think this is fixing the issue the wrong way. Preferably you want to fix the shutdown procedure so it waits for task completion and only then shuts down the http client. Right now that's exactly the other way around. Also instead of doing a `shutdownNow()` on the executor service you can consider using the `MoreExecutors.shutdownAndAwaitTermination` method to handle this, which takes care of a lot of the shutdown logic.

**Comment by rogierslag** [comment]
True, that is why I mentioned this was "slightly" hacky. However as a library we should code defensively

**Comment by AlexKolpa** [comment]
>However as a library we should code defensively

If the shutdown procedure is fixed, this should not be needed at all, since any form of hard termination of the system would kill everything at once, not just the http client.

**Comment by michaeldejong** [comment]
This is not how we program. 👎  If you want to not trigger this exception, track the shutdown in the Consultant class, or better yet, fix your shutdown.

**Pull request closed without merging**
